kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-calc
  template:
    metadata:
      labels:
        app: my-calc
    spec:
      containers:
        - name: my-calc
          image: localhost:5000/my-calc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: my-calc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector:
    app: my-calc