version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ahsanr478/react-calc:intial
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - '80:3000'
    networks:
      - webnet
networks:
  webnet: